# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # This gives the default GITHUB_TOKEN the permission to push to your repository.
    # This is required for the JamesIves/github-pages-deploy-action to work.
    permissions:
      contents: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4 # Use a more recent version of the checkout action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Use a more recent version of the setup action
      
      # This step builds your Docker image.
      # Create React App's build script will automatically find and use the .env file
      # that you have committed to your repository.
      # We have removed the entire 'build-args' section.
      - name: Build and export to directory
        uses: docker/build-push-action@v5 # Use a more recent version of the build action
        with:
          context: .
          load: true
          tags: love-app:latest

      - name: Create build directory
        run: mkdir -p build_output

      - name: Copy static files from Docker image
        run: |
          docker create --name temp_container love-app:latest
          docker cp temp_container:/usr/share/nginx/html/. ./build_output
          docker rm temp_container

      # This step deploys the contents of 'build_output' to the 'gh-pages' branch.
      # It will use the GITHUB_TOKEN by default because we have not specified an ssh-key.
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build_output